In [1]:
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_json('data/cowrie_1.json',lines=True)
data.head()

compCS data      dst_ip  dst_port  duration  \
0     NaN  NaN  10.10.0.13    2222.0       NaN   
1  [none]  NaN         NaN       NaN       NaN   
2     NaN  NaN         NaN       NaN       NaN   
3     NaN  NaN         NaN       NaN   9.96463   
4     NaN  NaN  10.10.0.13    2222.0       NaN   

                                               encCS                 eventid  \
0                                                NaN  cowrie.session.connect   
1  [aes128-ctr, aes192-ctr, aes256-ctr, aes256-cb...   cowrie.client.version   
2                                                NaN    cowrie.login.success   
3                                                NaN   cowrie.session.closed   
4                                                NaN  cowrie.session.connect   

   height input  isError  ...   size         src_ip src_port  \
0     NaN   NaN      0.0  ...    NaN  116.31.116.16  39547.0   
1     NaN   NaN      0.0  ...    NaN  116.31.116.16      NaN   
2     NaN   NaN      0.0  ...    NaN  116.31.116.16      NaN   
3     NaN   NaN      0.0  ...    NaN  116.31.116.16      NaN   
4     NaN   NaN      0.0  ...    NaN  116.31.116.16  22040.0   

                                              system  \
0                cowrie.ssh.factory.CowrieSSHFactory   
1             HoneyPotSSHTransport,523,116.31.116.16   
2  SSHService 'ssh-userauth' on HoneyPotSSHTransp...   
3             HoneyPotSSHTransport,523,116.31.116.16   
4                cowrie.ssh.factory.CowrieSSHFactory   

                   timestamp ttylog  url username        version  width  
0 2017-07-03 18:30:07.569246    NaN  NaN      NaN            NaN    NaN  
1 2017-07-03 18:30:08.235671    NaN  NaN      NaN  SSH-2.0-PUTTY    NaN  
2 2017-07-03 18:30:10.585142    NaN  NaN     root            NaN    NaN  
3 2017-07-03 18:30:17.902600    NaN  NaN      NaN            NaN    NaN  
4 2017-07-03 18:30:44.657703    NaN  NaN      NaN            NaN    NaN  

[5 rows x 29 columns]

In [3]:
data['eventid'] = LabelEncoder().fit_transform(data['eventid'].astype('str').values)

In [4]:
data_agg = data.groupby('session',as_index=False).agg(lambda x: x.tolist())

In [5]:
agg = pd.DataFrame()
agg['eventid'] = data_agg['eventid']

In [6]:
agg.head()

eventid
0  [12, 10, 8, 3, 4, 3, 2, 3, 4, 3, 4, 3, 4, 4, 4...
1                                 [12, 10, 8, 7, 11]
2                                    [12, 1, 10, 11]
3                                           [12, 11]
4                                    [12, 1, 10, 11]

In [7]:
np.array(agg.loc[0])

array([list([12, 10, 8, 3, 4, 3, 2, 3, 4, 3, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 3, 4, 7, 11])],
      dtype=object)

In [24]:
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
a = np.array(a)
a = a.reshape(-1,1)

In [25]:
a

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [26]:
model = hmm.GaussianHMM(n_components=14, covariance_type="full")
model.fit(a)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function distribute_covar_matrix_to_match_covariance_type is deprecated; The function distribute_covar_matrix_to_match_covariance_typeis deprecated in 0.18 and will be removed in 0.20.
  warnings.warn(msg, category=DeprecationWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20.
  warnings.warn(msg, category=DeprecationWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20.
  warnings.warn(ms

GaussianHMM(algorithm='viterbi', covariance_type='full', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=14, n_iter=10, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)

In [27]:
model.predict(a)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20.
  warnings.warn(msg, category=DeprecationWarning)
/Users/sohamdeshmukh/Library/Python/3.6/lib/python/site-packages/hmmlearn/base.py:451: RuntimeWarning: divide by zero encountered in log
  n_samples, n_components, np.log(self.startprob_),
/Users/sohamdeshmukh/Library/Python/3.6/lib/python/site-packages/hmmlearn/base.py:452: RuntimeWarning: divide by zero encountered in log
  np.log(self.transmat_), framelogprob)


array([ 3,  3, 12, 11, 13,  4,  6,  8,  2, 10,  7,  9,  5,  5])

In [28]:
model.startprob_

array([2.26740462e-063, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.75786247e-044,
       3.59126125e-014, 9.70467562e-225])

In [29]:
model.transmat_

array([[2.73364091e-003, 2.09985936e-075, 1.98632512e-048,
        5.89277906e-041, 3.38035949e-001, 6.40223450e-097,
        6.38962595e-011, 2.71196887e-067, 4.81172135e-027,
        7.70858504e-080, 2.29174721e-064, 6.79309147e-008,
        1.93634254e-017, 6.59230342e-001],
       [2.05812159e-161, 5.10365204e-002, 8.33533688e-045,
        6.89630574e-270, 1.53545778e-137, 4.15224216e-001,
        6.53840430e-105, 3.00200268e-006, 3.40556328e-073,
        5.33736261e-001, 4.07608600e-020, 1.81832683e-201,
        4.86584402e-229, 1.08058210e-159],
       [7.77612714e-125, 1.39488141e-006, 5.27859988e-025,
        1.59119433e-288, 4.10592937e-225, 6.39346895e-017,
        1.39408763e-141, 8.58085697e-003, 4.80179236e-059,
        2.47040090e-010, 9.91417748e-001, 8.79246644e-196,
        1.12307845e-234, 1.63001559e-230],
       [4.48361127e-010, 1.94246077e-175, 1.00930121e-158,
        4.44656120e-001, 5.20520463e-048, 1.16770855e-202,
        6.94277782e-082, 1.31964097e-168, 7.4