In [1]:
import numpy as np
import pandas as pd
import hmm
from tqdm import tqdm_notebook as tqdm

# Hidden Markov Model

In [2]:
N = 3
M = 13
T = 5

In [3]:
mod = hmm.HMM(N, M, T)

In [4]:
O = np.array([[12, 9, 8, 10, 11], [12, 9, 8, 7, 11], [12, 11, 10, 11, 11]])

In [5]:
O1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 5, 4, 6]])

In [6]:
print (mod.train(O))

Update #1 Log Probability: -3.929047649953784 -- Mean Error 0.01882563907331964
Update #1 Probability: 0.003842038568782924
Update #2 Log Probability: -1.3116329088839587 -- Mean Error 0.002070591732751296
Update #2 Probability: 0.006515892962041213
Update #3 Log Probability: -0.9442476988824366 -- Mean Error 0.0049056681142002215
Update #3 Probability: 0.019617065842991218
Update #4 Log Probability: -0.6908609028339603 -- Mean Error 0.002681959101661279
Update #4 Probability: 0.041953433701830606
Update #5 Log Probability: -0.6061207449671974 -- Mean Error 0.0006578414339469393
Update #5 Probability: 0.05409710949041727
Update #6 Log Probability: -0.5454835836168311 -- Mean Error 0.0007454293095272684
Update #6 Probability: 0.06488991634584228
Update #7 Log Probability: -0.4881619314993349 -- Mean Error 0.0005748646712136001
Update #7 Probability: 0.07706561453550949
Update #8 Log Probability: -0.46428386622124984 -- Mean Error 8.582811938731491e-05
Update #8 Probability: 0.0827886845

In [7]:
mod.full_prob(mod.forward(O[2]))

0.24999917273580094

In [8]:
mod.viterbi([1, 1, 0, 1, 0])

array([0, 0, 0, 0, 0])

In [9]:
mod.likelihood(O[1])

0.0

# Markov Chain

In [10]:
import numpy as np
import pandas as pd
import random
from markovchain import MarkovChain

In [11]:
mod = MarkovChain(states=[0, 1, 2, 3], initial=[0, 1, 0, 0])

In [12]:
mod.train([[0, 1, 2, 1], [0, 1, 2, 1, 3]])

In [13]:
mod.transition

array([[0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.66666667, 0.33333333],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [14]:
mod.get_probability([0, 1, 3])

0.3333333333333333

# hmmlearn

In [15]:
from hmmlearn.hmm import GaussianHMM

In [16]:
model = GaussianHMM(n_components=3)

In [17]:
X1 = [[12], [9], [8], [10], [11]]
X2 = [[12], [6], [8], [7], [11]]
X3 = [[12], [11], [10], [11], [11]]

X = np.concatenate([X1, X2, X3])
lengths = [len(X1), len(X2), len(X3)]


model.fit(X, lengths)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function distribute_covar_matrix_to_match_covariance_type is deprecated; The function distribute_covar_matrix_to_match_covariance_typeis deprecated in 0.18 and will be removed in 0.20.
  warnings.warn(msg, category=DeprecationWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20.
  warnings.warn(msg, category=DeprecationWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20.
  warnings.warn(msg, category=DeprecationWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:77: DeprecationWa

GaussianHMM(algorithm='viterbi', covariance_type='diag', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=3, n_iter=10, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)

In [18]:
X

array([[12],
       [ 9],
       [ 8],
       [10],
       [11],
       [12],
       [ 6],
       [ 8],
       [ 7],
       [11],
       [12],
       [11],
       [10],
       [11],
       [11]])

In [19]:
model.score(X3)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function log_multivariate_normal_density is deprecated; The function log_multivariate_normal_density is deprecated in 0.18 and will be removed in 0.20.
  warnings.warn(msg, category=DeprecationWarning)


-1.5117119376714343

In [20]:
X3 = [[12],[11], [11]]

In [21]:
model._covars_

array([[0.00336289],
       [1.12710682],
       [0.20236964]])